name: Generate Snake Animation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: d-beloved/snk@main
        id: snake-gif
        with:
          github_user_name: d-beloved
          outputs: dist/github-graph-snake.svg
          
      - uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}