name: Update README with Featured Repos

on:
  workflow_dispatch:     # Manual trigger
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Fetch and update README
        run: |
          npm install @octokit/graphql
          node update-readme.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes detected in README.md"
          else
            git commit -m "Updated README with latest featured repos"
            git push
          fi